{% set name = "cytoplay" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67d0adf28b570e637e54adb11055cab16a90e5744e6b7e3faaa4c920f32b1fb6
build:
  skip: true  # [win]
  number: 3
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake >=3.14
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - setuptools
    - python
    - pip
    - libblas
    - liblapack
    - pybind11
    - freeglut  # [linux]
    - xorg-libxi
    - xorg-libxmu
    - xorg-libx11  # [linux]
    - xorg-xproto  # [linux]
    - glew
    - zlib
    - ncurses      # [linux] 
    - libgl-devel                    # [linux]
  run:
    - python
    - xorg-libx11  # [linux]
    - ncurses      # [linux]
    - libgl        # [linux]
test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - cytosim2D
about:
  home: http://cytosim.org/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Cytosim: Langevin dynamics of active polymer networks"
  doc_url: https://cytosim.gitlab.io/cytosim/doc/code/doxygen/index.html
  dev_url: https://gitlab.com/f-nedelec/cytosim

extra:
  recipe-maintainers:
    - SergeDmi
